// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserService.Data;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(AppicationDbContext))]
    [Migration("20240112100317_SeedDataPermission")]
    partial class SeedDataPermission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserService.Data.Permission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            Id = "0deebcd8-395a-4f7e-a1a5-c4a7da44d9f3",
                            PermissionName = "GetAll:Course"
                        },
                        new
                        {
                            Id = "04241c24-424c-4969-be8b-5fb0849e8b10",
                            PermissionName = "Edit:Course"
                        },
                        new
                        {
                            Id = "9c98de9a-581d-41b1-b35b-580e83e07b49",
                            PermissionName = "Delete:Course"
                        },
                        new
                        {
                            Id = "21eb64fb-0a79-43ef-9869-7d52b04d0719",
                            PermissionName = "GetActive:Course"
                        },
                        new
                        {
                            Id = "e5c73991-de58-43c9-8779-0e6be0504f48",
                            PermissionName = "GetById:Course"
                        },
                        new
                        {
                            Id = "133aa8e6-c138-489d-9005-e2ada7791b82",
                            PermissionName = "Approve:Course"
                        },
                        new
                        {
                            Id = "c445c3db-c84c-45c4-a1ca-eb4eefb07f07",
                            PermissionName = "Create:Course"
                        },
                        new
                        {
                            Id = "1d880d82-fa99-4ceb-9769-e79a08a328b0",
                            PermissionName = "Download:Course"
                        },
                        new
                        {
                            Id = "2db9b301-1aa5-4aee-a8b9-bacd42d161ae",
                            PermissionName = "Setting:Course"
                        },
                        new
                        {
                            Id = "b12f45d2-3581-41b4-98c5-83de8d3c5cdf",
                            PermissionName = "GetAll:Class"
                        },
                        new
                        {
                            Id = "beff089b-f5f8-4663-acad-0e45079dfb80",
                            PermissionName = "Edit:Class"
                        },
                        new
                        {
                            Id = "8e093ea2-c9a4-4ab4-9c6b-94afcc057f11",
                            PermissionName = "Delete:Class"
                        },
                        new
                        {
                            Id = "172fcfa0-80e3-4154-b51d-9dc9a9d35931",
                            PermissionName = "GetActive:Class"
                        },
                        new
                        {
                            Id = "4c27715c-81f8-4ffc-afd4-04c59e0a3b30",
                            PermissionName = "GetById:Class"
                        },
                        new
                        {
                            Id = "bfb96bf8-032b-4b6c-b4fc-0e44424be6bf",
                            PermissionName = "Approve:Class"
                        },
                        new
                        {
                            Id = "27e1010f-c145-4056-8328-d2fb9c25a66b",
                            PermissionName = "Create:Class"
                        },
                        new
                        {
                            Id = "576c7f4c-84c8-4a9c-a479-c1dface4e0e1",
                            PermissionName = "Download:Class"
                        },
                        new
                        {
                            Id = "161b515c-e9f4-4c27-89af-1fe0b97c3439",
                            PermissionName = "Setting:Class"
                        },
                        new
                        {
                            Id = "65f3809f-af7e-4a10-97f0-5010521c759f",
                            PermissionName = "GetAll:PrivateFile"
                        },
                        new
                        {
                            Id = "3697224a-76bd-494c-a008-f587e53089aa",
                            PermissionName = "Edit:PrivateFile"
                        },
                        new
                        {
                            Id = "747a0551-858c-4500-a271-d21c218eaf69",
                            PermissionName = "Delete:PrivateFile"
                        },
                        new
                        {
                            Id = "0d05e118-9845-42f9-9b87-dda61a05cbeb",
                            PermissionName = "GetActive:PrivateFile"
                        },
                        new
                        {
                            Id = "22ce34b9-e892-48a6-8460-44ffdca43500",
                            PermissionName = "GetById:PrivateFile"
                        },
                        new
                        {
                            Id = "c8cde731-c200-4aeb-b6ec-e26db20e8be5",
                            PermissionName = "Approve:PrivateFile"
                        },
                        new
                        {
                            Id = "6b3da046-716d-4c11-b892-fe4f7cf2aa3b",
                            PermissionName = "Create:PrivateFile"
                        },
                        new
                        {
                            Id = "c1be278e-bf60-4bdd-8ae0-42cec9683ec8",
                            PermissionName = "Download:PrivateFile"
                        },
                        new
                        {
                            Id = "7085381e-7347-4ce0-b81e-a041593253e6",
                            PermissionName = "Setting:PrivateFile"
                        },
                        new
                        {
                            Id = "7f223eaf-35b0-4a24-ae25-a1b346b1696d",
                            PermissionName = "GetAll:Topic"
                        },
                        new
                        {
                            Id = "8def499b-9847-4102-9174-5040b5879c9f",
                            PermissionName = "Edit:Topic"
                        },
                        new
                        {
                            Id = "bb203eeb-b5b9-4169-84b3-75f6d1e71a0d",
                            PermissionName = "Delete:Topic"
                        },
                        new
                        {
                            Id = "d14c91da-1848-4438-b5be-6efa8d863fe7",
                            PermissionName = "GetActive:Topic"
                        },
                        new
                        {
                            Id = "2390aa78-4893-4929-9498-46a00524da0f",
                            PermissionName = "GetById:Topic"
                        },
                        new
                        {
                            Id = "4618b63e-71cf-4321-a677-8d7f6f1f6b10",
                            PermissionName = "Approve:Topic"
                        },
                        new
                        {
                            Id = "23630dd9-9b31-485d-963e-d9c452255c28",
                            PermissionName = "Create:Topic"
                        },
                        new
                        {
                            Id = "6dc986c9-ee5d-4d5f-9a54-6dda1e9e3f64",
                            PermissionName = "Download:Topic"
                        },
                        new
                        {
                            Id = "e1fccd7d-c301-41f0-8dc6-024330115904",
                            PermissionName = "Setting:Topic"
                        },
                        new
                        {
                            Id = "643cc574-84c5-4b7f-b1eb-b0398704737c",
                            PermissionName = "GetAll:Lesson"
                        },
                        new
                        {
                            Id = "a4cfa290-07c4-4fc7-98fb-36a48e4a41ac",
                            PermissionName = "Edit:Lesson"
                        },
                        new
                        {
                            Id = "f46163be-d5f9-4061-a712-312aa4392838",
                            PermissionName = "Delete:Lesson"
                        },
                        new
                        {
                            Id = "de0596e6-1a03-4413-967f-3fc6a34e0da8",
                            PermissionName = "GetActive:Lesson"
                        },
                        new
                        {
                            Id = "0b7795b3-3d11-4609-8808-c0ce7e9e7810",
                            PermissionName = "GetById:Lesson"
                        },
                        new
                        {
                            Id = "da47fa11-d385-4ab3-9573-a4468c7894f5",
                            PermissionName = "Approve:Lesson"
                        },
                        new
                        {
                            Id = "0edbd6fc-ff60-4909-bf67-39feba968da7",
                            PermissionName = "Create:Lesson"
                        },
                        new
                        {
                            Id = "5ce1011a-aa81-4804-8fa4-0301db7419e3",
                            PermissionName = "Download:Lesson"
                        },
                        new
                        {
                            Id = "44f71c08-f359-4272-976d-b62709d7a40c",
                            PermissionName = "Setting:Lesson"
                        },
                        new
                        {
                            Id = "44138a91-ab5e-4db7-938a-7e9280349a71",
                            PermissionName = "GetAll:Resource"
                        },
                        new
                        {
                            Id = "e0c60dd4-189d-472c-bace-2f80ba6d06f2",
                            PermissionName = "Edit:Resource"
                        },
                        new
                        {
                            Id = "4214a491-e17b-4013-8535-fd194864a27e",
                            PermissionName = "Delete:Resource"
                        },
                        new
                        {
                            Id = "da995c85-6a96-4f6b-9593-551cf6bd8adb",
                            PermissionName = "GetActive:Resource"
                        },
                        new
                        {
                            Id = "17e0ce41-4fd0-4a30-9056-8408ff8cd3f5",
                            PermissionName = "GetById:Resource"
                        },
                        new
                        {
                            Id = "40a39f85-76b3-4c0a-8225-f1f090d7ea9c",
                            PermissionName = "Approve:Resource"
                        },
                        new
                        {
                            Id = "2129f409-98d9-47b8-b031-e168ee26f952",
                            PermissionName = "Create:Resource"
                        },
                        new
                        {
                            Id = "c63e4d67-c342-474e-b584-62e3c28517d3",
                            PermissionName = "Download:Resource"
                        },
                        new
                        {
                            Id = "3e14ac83-c029-4f26-b1a6-3df525c905ba",
                            PermissionName = "Setting:Resource"
                        },
                        new
                        {
                            Id = "64487dbc-4c84-481b-9afa-f38d0b1b9ea0",
                            PermissionName = "GetAll:Exam"
                        },
                        new
                        {
                            Id = "719e3528-7dfc-4954-878a-f59fb21c4527",
                            PermissionName = "Edit:Exam"
                        },
                        new
                        {
                            Id = "20a3f17c-0938-48ea-8f29-f8fbbac2fd08",
                            PermissionName = "Delete:Exam"
                        },
                        new
                        {
                            Id = "7fe2a429-f135-4351-856b-ec6bef6effdb",
                            PermissionName = "GetActive:Exam"
                        },
                        new
                        {
                            Id = "d4f1b348-f29c-423b-876b-77d6def49a10",
                            PermissionName = "GetById:Exam"
                        },
                        new
                        {
                            Id = "823d7468-c573-4166-861e-397c15688b63",
                            PermissionName = "Approve:Exam"
                        },
                        new
                        {
                            Id = "d9b70fff-7391-4717-8a91-375f5730f238",
                            PermissionName = "Create:Exam"
                        },
                        new
                        {
                            Id = "f6e76145-bb15-478c-a149-f572853b3d39",
                            PermissionName = "Download:Exam"
                        },
                        new
                        {
                            Id = "dcfe925e-f0dd-4e4b-9c2b-9d3b42ca7d19",
                            PermissionName = "Setting:Exam"
                        },
                        new
                        {
                            Id = "6092bde7-4184-4757-95f2-f23cf61b4d13",
                            PermissionName = "GetAll:Question"
                        },
                        new
                        {
                            Id = "1f40dfa3-cf4f-481f-b1b1-c926c5f493bd",
                            PermissionName = "Edit:Question"
                        },
                        new
                        {
                            Id = "4c2245d4-ebf3-4f28-9967-32f88aad3809",
                            PermissionName = "Delete:Question"
                        },
                        new
                        {
                            Id = "3546ada9-6c21-403d-a649-dc7ce6e8171a",
                            PermissionName = "GetActive:Question"
                        },
                        new
                        {
                            Id = "84ad59f2-c3eb-4d26-a0f5-ce2f198cc8fc",
                            PermissionName = "GetById:Question"
                        },
                        new
                        {
                            Id = "015433e8-d791-46d4-aebf-c19950ce9dff",
                            PermissionName = "Approve:Question"
                        },
                        new
                        {
                            Id = "07bc8f01-ffc2-4d7e-a0e2-879f6c6250e9",
                            PermissionName = "Create:Question"
                        },
                        new
                        {
                            Id = "0007584b-2296-4002-a6cf-8b69ca33e1a7",
                            PermissionName = "Download:Question"
                        },
                        new
                        {
                            Id = "0fcb2836-1937-4621-834a-e1ff0afaf117",
                            PermissionName = "Setting:Question"
                        },
                        new
                        {
                            Id = "7608e527-afc4-498f-b4aa-199b43900fed",
                            PermissionName = "GetAll:Answer"
                        },
                        new
                        {
                            Id = "d2d2ff99-e5e7-4732-8598-75f219734dc9",
                            PermissionName = "Edit:Answer"
                        },
                        new
                        {
                            Id = "2ed5a1c5-37b7-4a55-b342-82e3c3544677",
                            PermissionName = "Delete:Answer"
                        },
                        new
                        {
                            Id = "f5be4d7c-6762-48b2-a93c-0b9a05e12923",
                            PermissionName = "GetActive:Answer"
                        },
                        new
                        {
                            Id = "6525b80e-b1f8-4bf1-a998-c615fdf105a2",
                            PermissionName = "GetById:Answer"
                        },
                        new
                        {
                            Id = "5a7839b3-8fcb-4542-bd12-a5614b47db3c",
                            PermissionName = "Approve:Answer"
                        },
                        new
                        {
                            Id = "e14549de-bd14-4ad0-bf4c-95fef6247832",
                            PermissionName = "Create:Answer"
                        },
                        new
                        {
                            Id = "7eb0165e-1239-49e1-ac2c-e2e5f1fcc963",
                            PermissionName = "Download:Answer"
                        },
                        new
                        {
                            Id = "963b45f5-a2f3-4541-ba4d-35eba50d8bbc",
                            PermissionName = "Setting:Answer"
                        },
                        new
                        {
                            Id = "e97594ca-314a-48dc-8a46-fb5bd8ab758a",
                            PermissionName = "GetAll:ExamQuestion"
                        },
                        new
                        {
                            Id = "7e582a5e-89d2-4481-9680-4ccf8bbfbc5e",
                            PermissionName = "Edit:ExamQuestion"
                        },
                        new
                        {
                            Id = "c09aec01-6043-4bfe-85e1-a8e28d5a1dc2",
                            PermissionName = "Delete:ExamQuestion"
                        },
                        new
                        {
                            Id = "99bace0c-56c7-438c-a403-b00b6e90da4e",
                            PermissionName = "GetActive:ExamQuestion"
                        },
                        new
                        {
                            Id = "766e019e-558a-4e3e-aa72-37144761daf5",
                            PermissionName = "GetById:ExamQuestion"
                        },
                        new
                        {
                            Id = "7fb8398b-b509-4494-b477-77351bf1f7ec",
                            PermissionName = "Approve:ExamQuestion"
                        },
                        new
                        {
                            Id = "9c2d8c3a-2d83-4240-89f4-2a42789e225a",
                            PermissionName = "Create:ExamQuestion"
                        },
                        new
                        {
                            Id = "bc7e6177-fe24-487b-a736-588bcfa4d67b",
                            PermissionName = "Download:ExamQuestion"
                        },
                        new
                        {
                            Id = "eac7a448-a794-4d00-aa25-49d6a6d3318b",
                            PermissionName = "Setting:ExamQuestion"
                        },
                        new
                        {
                            Id = "2e6daa10-3aba-49b4-a3f4-f31276d31c60",
                            PermissionName = "GetAll:Notification"
                        },
                        new
                        {
                            Id = "6b52267d-f873-4a39-a0fc-7a2e2fd4ddca",
                            PermissionName = "Edit:Notification"
                        },
                        new
                        {
                            Id = "dc4e281c-062c-48c0-b529-981c7fe9d417",
                            PermissionName = "Delete:Notification"
                        },
                        new
                        {
                            Id = "3aa888f6-ed66-462d-9529-7f87b4e3810b",
                            PermissionName = "GetActive:Notification"
                        },
                        new
                        {
                            Id = "6239daf1-b0ec-439b-b77c-57975ce6057b",
                            PermissionName = "GetById:Notification"
                        },
                        new
                        {
                            Id = "563953e4-59bb-4790-96df-66f9fac572e5",
                            PermissionName = "Approve:Notification"
                        },
                        new
                        {
                            Id = "75bf160c-3e33-42ba-a70f-d4329d1db33a",
                            PermissionName = "Create:Notification"
                        },
                        new
                        {
                            Id = "5753c5d2-4841-424c-8e08-124a89fd19e8",
                            PermissionName = "Download:Notification"
                        },
                        new
                        {
                            Id = "2c713558-9f7c-43e5-bb5b-3659922263e6",
                            PermissionName = "Setting:Notification"
                        },
                        new
                        {
                            Id = "65268283-a1c2-4aa0-bf38-1da7100a1ece",
                            PermissionName = "GetAll:System"
                        },
                        new
                        {
                            Id = "1e3d847b-3638-4825-ae9c-260c0dc43e95",
                            PermissionName = "Edit:System"
                        },
                        new
                        {
                            Id = "77bfb638-6492-41a1-8b7b-6145a3a71507",
                            PermissionName = "Delete:System"
                        },
                        new
                        {
                            Id = "0808ffa7-e19f-4790-bb4d-bfcace80dd57",
                            PermissionName = "GetActive:System"
                        },
                        new
                        {
                            Id = "ddd1fb2b-46b9-4916-a8c5-2f9cccf2eca2",
                            PermissionName = "GetById:System"
                        },
                        new
                        {
                            Id = "c628321f-5bc1-4458-950f-7c8b88908844",
                            PermissionName = "Approve:System"
                        },
                        new
                        {
                            Id = "a67b57fc-0f08-4115-b914-4216c2ff750e",
                            PermissionName = "Create:System"
                        },
                        new
                        {
                            Id = "fd227e0b-e454-4c93-9f7f-359d06fa2b22",
                            PermissionName = "Download:System"
                        },
                        new
                        {
                            Id = "a3f881d5-2c10-4026-bdae-ee131bc21773",
                            PermissionName = "Setting:System"
                        },
                        new
                        {
                            Id = "dfaea302-356c-4f4d-8b29-9939a6386822",
                            PermissionName = "GetAll:User"
                        },
                        new
                        {
                            Id = "d03bd4dc-e0bc-4e4e-b4be-4b44f4a51778",
                            PermissionName = "Edit:User"
                        },
                        new
                        {
                            Id = "c85a2207-371c-44ac-9cbc-dce5c7faa18f",
                            PermissionName = "Delete:User"
                        },
                        new
                        {
                            Id = "c3027ab4-2f9c-4c1d-b7ba-3d15c7aa903e",
                            PermissionName = "GetActive:User"
                        },
                        new
                        {
                            Id = "5d7d89d0-b237-4890-ae0b-ab1571488562",
                            PermissionName = "GetById:User"
                        },
                        new
                        {
                            Id = "d6b9add3-bfa1-450b-9572-76fd8f33090f",
                            PermissionName = "Approve:User"
                        },
                        new
                        {
                            Id = "bde3740d-0ad3-4b37-a6bf-6c9fe03f8679",
                            PermissionName = "Create:User"
                        },
                        new
                        {
                            Id = "771911ff-a27f-4545-baec-b9525924869c",
                            PermissionName = "Download:User"
                        },
                        new
                        {
                            Id = "b23af460-317f-4e57-8acf-fafe0ee07339",
                            PermissionName = "Setting:User"
                        });
                });

            modelBuilder.Entity("UserService.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
